
version: '3'
services:
  server:
    container_name: server
    restart: always
    image: shivankarp/microj_server:latest
    ports:
      - '3000:3000'

  judge:
    container_name: judge
    restart: always
    image: shivankarp/microj_judge:latest

  mongo:
    container_name: mongo_service
    image: 'mongo:7'
    expose: 
      - 27017

  redis:
    container_name: redis_service
    image: 'redis:4.0.11'
    expose:
      - 6379

  rabbitmq:
    container_name: queue_service
    image: rabbitmq:management
    expose:
      - 5672
    ports:
      - '15672:15672'

  frontend:
    container_name: frontend
    restart: always
    image: shivankarp/microj_frontend:latest
    ports:
      - '4000:3000'
    depends_on:
      - server
